/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.book_store;

import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import Utils.*;

/**
 *
 * @author Hazux
 */
public class MainFrame extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setTitle("Hệ thống nhà sách");
        setIconImage(image);
        setClock();

    }
    ImageIcon icon = new ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\Book_Store\\src\\main\\java\\IconPack\\book.png");
    Image image = icon.getImage();

    //SetTime
    @Override
    public void run() {
        while (true) {
            try {
                Date now = new Date();
                SimpleDateFormat timeFormater = new SimpleDateFormat("hh:mm:ss aa");
                SimpleDateFormat dateFormater = new SimpleDateFormat("dd:MM:yyyy");
                lblTime.setText(timeFormater.format(now));
                lblDate.setText(dateFormater.format(now));

                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                break;
            }
        }
    }

    private void setClock() {
        // TODO add your handling code here:
        Thread time = new Thread(this);
        time.start();
    }

    //
    void openCaiDat() {
//        if (Auth.isLogin()) {
        Cai_Dat fr = new Cai_Dat();
        fr.setVisible(true);
//        } else {
//            MgsBox.alert(this, "Vui lòng đăng nhập!");
//        }
    }
    void dangXuat() {
        Auth.clear();
        setVisible(false);
        Login lg= new Login();
        lg.setVisible(true);
    }
    
    void openKhuyenMai() {
        Khuyen_Mai fr = new Khuyen_Mai();
        fr.setVisible(true);
    }

    void openQuanLyKho() {
        Quan_Ly_Kho fr = new Quan_Ly_Kho();
        fr.setVisible(true);
    }

    void openQuanLyNV() {
        Quan_Ly_Nhan_Vien fr = new Quan_Ly_Nhan_Vien();
        fr.setVisible(true);
    }

    void openQuanLySach() {
        Quan_Ly_Sach fr = new Quan_Ly_Sach();
        fr.setVisible(true);
    }

    void openThanhToan() {
        Thanh_Toan fr = new Thanh_Toan();
        fr.setVisible(true);
    }

    void openThongKe(int index) {
        Thong_Ke fr = new Thong_Ke();
        fr.setVisible(true);
        fr.selectTab(index);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnBook = new javax.swing.JButton();
        btnStaff = new javax.swing.JButton();
        btnRevenue = new javax.swing.JButton();
        btnDiscount = new javax.swing.JButton();
        btnCash = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuSys = new javax.swing.JMenu();
        mniLogout = new javax.swing.JMenu();
        mniSetting = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mniExit = new javax.swing.JMenuItem();
        mnuManagement = new javax.swing.JMenu();
        mniCash = new javax.swing.JMenuItem();
        mniStaff = new javax.swing.JMenuItem();
        mniBook = new javax.swing.JMenuItem();
        mniWarehouse = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniDiscount = new javax.swing.JMenuItem();
        mnuStat = new javax.swing.JMenu();
        mniRevenue = new javax.swing.JMenuItem();
        mniRevenueBook = new javax.swing.JMenuItem();
        mniBill = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mniGuide = new javax.swing.JMenuItem();
        mniAbout = new javax.swing.JMenuItem();

        jMenuItem8.setText("jMenuItem8");

        jMenuItem11.setText("jMenuItem11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDate.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\Book_Store\\src\\main\\java\\IconPack\\calendar.png")); // NOI18N
        lblDate.setText("Date:");

        lblTime.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\Book_Store\\src\\main\\java\\IconPack\\clock.png")); // NOI18N
        lblTime.setText("Time:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(lblTime))
                .addContainerGap())
        );

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nhà sách ABC");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\Book_Store\\src\\main\\java\\IconPack\\z4538359892432_44042f22755b69dc7d2ddea965d56716 (1).jpg")); // NOI18N

        btnBook.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\Book_Store\\src\\main\\java\\IconPack\\Book_25711.png")); // NOI18N
        btnBook.setText("Sách");
        btnBook.setHideActionText(true);
        btnBook.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBook.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        btnStaff.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\Book_Store\\src\\main\\java\\IconPack\\edit_user_student_staff_person_icon-icons.com_75492.png")); // NOI18N
        btnStaff.setText("Nhân viên");
        btnStaff.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnStaff.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffActionPerformed(evt);
            }
        });

        btnRevenue.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\Book_Store\\src\\main\\java\\IconPack\\analytics_income_increase_chart_growth_profit_revenue_icon_232603.png")); // NOI18N
        btnRevenue.setText("Doanh Thu");
        btnRevenue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRevenue.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRevenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevenueActionPerformed(evt);
            }
        });

        btnDiscount.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\Book_Store\\src\\main\\java\\IconPack\\sale_5099.png")); // NOI18N
        btnDiscount.setText("Khuyến mãi");
        btnDiscount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDiscount.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiscountActionPerformed(evt);
            }
        });

        btnCash.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\Book_Store\\src\\main\\java\\IconPack\\pay_perclick_icon-icons.com_66877.png")); // NOI18N
        btnCash.setText("Thanh toán");
        btnCash.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCash.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashActionPerformed(evt);
            }
        });

        mnuSys.setText("Hệ thống");

        mniLogout.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\Book_Store\\src\\main\\java\\IconPack\\log_out_icon_128821.png")); // NOI18N
        mniLogout.setText("Đăng xuất");
        mniLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mniLogoutMouseClicked(evt);
            }
        });
        mniLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLogoutActionPerformed(evt);
            }
        });
        mnuSys.add(mniLogout);

        mniSetting.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\Book_Store\\src\\main\\java\\IconPack\\1904675-configuration-edit-gear-options-preferences-setting-settings_122525.png")); // NOI18N
        mniSetting.setText("Cài đặt");
        mniSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mniSettingMouseClicked(evt);
            }
        });
        mniSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSettingActionPerformed(evt);
            }
        });
        mnuSys.add(mniSetting);
        mnuSys.add(jSeparator2);

        mniExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mniExit.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\Book_Store\\src\\main\\java\\IconPack\\exit_closethesession_close_6317.png")); // NOI18N
        mniExit.setText("Kết thúc");
        mniExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExitActionPerformed(evt);
            }
        });
        mnuSys.add(mniExit);

        jMenuBar1.add(mnuSys);

        mnuManagement.setText("Quản lý");

        mniCash.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniCash.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\Book_Store\\src\\main\\java\\IconPack\\pay_perclick_icon-icons.com_66877.png")); // NOI18N
        mniCash.setText("Thanh toán");
        mniCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCashActionPerformed(evt);
            }
        });
        mnuManagement.add(mniCash);

        mniStaff.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mniStaff.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\Book_Store\\src\\main\\java\\IconPack\\edit_user_student_staff_person_icon-icons.com_75492.png")); // NOI18N
        mniStaff.setText("Nhân viên");
        mniStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniStaffActionPerformed(evt);
            }
        });
        mnuManagement.add(mniStaff);

        mniBook.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mniBook.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\Book_Store\\src\\main\\java\\IconPack\\Book_25711.png")); // NOI18N
        mniBook.setText("Sách");
        mniBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBookActionPerformed(evt);
            }
        });
        mnuManagement.add(mniBook);

        mniWarehouse.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mniWarehouse.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\Book_Store\\src\\main\\java\\IconPack\\iconfinder-warehouse-3992927_112594.png")); // NOI18N
        mniWarehouse.setText("Kho");
        mniWarehouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniWarehouseActionPerformed(evt);
            }
        });
        mnuManagement.add(mniWarehouse);
        mnuManagement.add(jSeparator1);

        mniDiscount.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mniDiscount.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\Book_Store\\src\\main\\java\\IconPack\\sale_5099.png")); // NOI18N
        mniDiscount.setText("Khuyến mãi");
        mniDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDiscountActionPerformed(evt);
            }
        });
        mnuManagement.add(mniDiscount);

        jMenuBar1.add(mnuManagement);

        mnuStat.setText("Thống kê");

        mniRevenue.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mniRevenue.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\Book_Store\\src\\main\\java\\IconPack\\analytics_income_increase_chart_growth_profit_revenue_icon_232603.png")); // NOI18N
        mniRevenue.setText("Doanh thu theo thời gian");
        mniRevenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniRevenueActionPerformed(evt);
            }
        });
        mnuStat.add(mniRevenue);

        mniRevenueBook.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mniRevenueBook.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\Book_Store\\src\\main\\java\\IconPack\\bookshelf_icon-icons.com_54414.png")); // NOI18N
        mniRevenueBook.setText("Doanh thu theo sách");
        mniRevenueBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniRevenueBookActionPerformed(evt);
            }
        });
        mnuStat.add(mniRevenueBook);

        mniBill.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mniBill.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\Book_Store\\src\\main\\java\\IconPack\\bill_payment_note_icon_143283.png")); // NOI18N
        mniBill.setText("Hoá đơn");
        mniBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBillActionPerformed(evt);
            }
        });
        mnuStat.add(mniBill);

        jMenuBar1.add(mnuStat);

        mnuHelp.setText("Trợ giúp");

        mniGuide.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mniGuide.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\Book_Store\\src\\main\\java\\IconPack\\travel-holiday-vacation-326_89089.png")); // NOI18N
        mniGuide.setText("Hướng dẫn sử dụng");
        mniGuide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniGuideActionPerformed(evt);
            }
        });
        mnuHelp.add(mniGuide);

        mniAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mniAbout.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\Book_Store\\src\\main\\java\\IconPack\\about_3697.png")); // NOI18N
        mniAbout.setText("Giới thiệu");
        mnuHelp.add(mniAbout);

        jMenuBar1.add(mnuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStaff)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRevenue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDiscount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCash)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRevenue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDiscount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniStaffActionPerformed
        // TODO add your handling code here:
        if (!Auth.isManager()) {
            MgsBox.alert(this, "Bạn không có quyền quản lý nhân viên!");
        } else {
            openQuanLyNV();

        }
    }//GEN-LAST:event_mniStaffActionPerformed

    private void btnRevenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevenueActionPerformed
        // TODO add your handling code here:
        openThongKe(2);
    }//GEN-LAST:event_btnRevenueActionPerformed

    private void btnCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashActionPerformed
        // TODO add your handling code here:
        openThanhToan();
    }//GEN-LAST:event_btnCashActionPerformed

    private void mniGuideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniGuideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniGuideActionPerformed

    private void mniExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExitActionPerformed
        // TODO add your handling code here
        System.exit(0);
    }//GEN-LAST:event_mniExitActionPerformed

    private void mniCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCashActionPerformed
        // TODO add your handling code here:
        openThanhToan();
    }//GEN-LAST:event_mniCashActionPerformed

    private void mniSettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniSettingMouseClicked
        // TODO add your handling code here:
        openCaiDat();


    }//GEN-LAST:event_mniSettingMouseClicked

    private void mniSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSettingActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_mniSettingActionPerformed

    private void mniBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBookActionPerformed
        // TODO add your handling code here:
        openQuanLySach();
    }//GEN-LAST:event_mniBookActionPerformed

    private void mniWarehouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniWarehouseActionPerformed
        // TODO add your handling code here:
        openQuanLyKho();
    }//GEN-LAST:event_mniWarehouseActionPerformed

    private void mniDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDiscountActionPerformed
        // TODO add your handling code here:
        openKhuyenMai();
    }//GEN-LAST:event_mniDiscountActionPerformed

    private void mniRevenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniRevenueActionPerformed
        // TODO add your handling code here:
        openThongKe(2);
    }//GEN-LAST:event_mniRevenueActionPerformed

    private void mniRevenueBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniRevenueBookActionPerformed
        // TODO add your handling code here:
        openThongKe(1);
    }//GEN-LAST:event_mniRevenueBookActionPerformed

    private void mniBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBillActionPerformed
        // TODO add your handling code here:
        openThongKe(0);
    }//GEN-LAST:event_mniBillActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
        openQuanLySach();
    }//GEN-LAST:event_btnBookActionPerformed

    private void btnStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffActionPerformed
        // TODO add your handling code here:
        if (!Auth.isManager()) {
            MgsBox.alert(this, "Bạn không có quyền quản lý nhân viên!");
        } else {
            openQuanLyNV();

        }
    }//GEN-LAST:event_btnStaffActionPerformed

    private void btnDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiscountActionPerformed
        // TODO add your handling code here:
        openKhuyenMai();
    }//GEN-LAST:event_btnDiscountActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void mniLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLogoutActionPerformed
        // TODO add your handling code here:
        dangXuat();
    }//GEN-LAST:event_mniLogoutActionPerformed

    private void mniLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniLogoutMouseClicked
        // TODO add your handling code here:
        dangXuat();
    }//GEN-LAST:event_mniLogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnCash;
    private javax.swing.JButton btnDiscount;
    private javax.swing.JButton btnRevenue;
    private javax.swing.JButton btnStaff;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblTime;
    private javax.swing.JMenuItem mniAbout;
    private javax.swing.JMenuItem mniBill;
    private javax.swing.JMenuItem mniBook;
    private javax.swing.JMenuItem mniCash;
    private javax.swing.JMenuItem mniDiscount;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenuItem mniGuide;
    private javax.swing.JMenu mniLogout;
    private javax.swing.JMenuItem mniRevenue;
    private javax.swing.JMenuItem mniRevenueBook;
    private javax.swing.JMenu mniSetting;
    private javax.swing.JMenuItem mniStaff;
    private javax.swing.JMenuItem mniWarehouse;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenu mnuManagement;
    private javax.swing.JMenu mnuStat;
    private javax.swing.JMenu mnuSys;
    // End of variables declaration//GEN-END:variables
}
